Added readme and feedback CRUD for Java SDK
RWS/languageweaver-sdk-samples pull request #15
Opened 2022-10-21 09:19 UTC by gmarginean-sdl

2022-10-27 12:38 UTC, LauraScurtu requested changes

2022-10-27 12:38 UTC, LauraScurtu commented on java/src/main/java/com/languageweaver/sdk/samples/feedback/EdgeFeedbackService.java
> +            System.out.println(feedback.getFeedbackId());
Same here

2022-10-27 12:38 UTC, LauraScurtu commented on java/src/main/java/com/languageweaver/sdk/samples/feedback/CloudFeedbackService.java
> +            System.out.println(feedback.getFeedbackId());
I would create separate methods for each operation.

2022-10-27 12:38 UTC, LauraScurtu commented on java/src/main/java/com/languageweaver/sdk/samples/feedback/FeedbackService.java
> +            System.out.println(feedback.getFeedbackId());
same

2022-10-27 12:38 UTC, LauraScurtu commented on dotnet/README.md
> +## .Net SDK samples
Add this information to the general readme.
We want to be displayed on this page: https://github.com/RWS/languageweaver-sdk-samples/.

2022-10-27 12:38 UTC, LauraScurtu commented on java/README.md
> +## Java SDK samples
Add this information to the general readme.
We want to be displayed on this page: https://github.com/RWS/languageweaver-sdk-samples/.

2022-12-09 14:23 UTC, alungu99 requested changes

2022-12-20 09:31 UTC, gmarginean-sdl commented on java/src/main/java/com/languageweaver/sdk/samples/feedback/CloudFeedbackService.java
> +            feedback = createFeedback();
Normally yes but for the purpose of this sample I think it is ok to have the full code in the methods.

2022-12-20 14:59 UTC, alungu99 requested changes

2022-12-20 14:59 UTC, alungu99 commented on java/src/main/java/com/languageweaver/sdk/samples/dictionaries/CloudDictionaryService.java
please resolve conflicts

2023-01-30 16:14 UTC, gmarginean-sdl commented
Created another [pull request](https://github.com/RWS/languageweaver-sdk-samples/pull/35) for these changes.

2023-01-30 16:14 UTC, closed without merging